# Generated by Django 3.2.13 on 2022-08-20 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_image'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('website', '0002_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
