# Generated by Django 3.2.13 on 2022-08-20 18:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_alter_post_image'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('website', '0004_customuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='Team',
        ),
    ]
