# Generated by Django 3.2.13 on 2022-08-20 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_customuser_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'team members'},
        ),
    ]
