# Generated by Django 3.2.13 on 2022-08-20 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_team_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'team member'},
        ),
    ]
