# Generated by Django 3.2.13 on 2022-08-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='./blog-1.jpg', upload_to='blog/'),
        ),
    ]
