# Generated by Django 3.2.13 on 2022-08-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='./blog-1.jpg', upload_to='statics\x07ssets\\img\x08log'),
        ),
    ]
