# Generated by Django 3.2.13 on 2022-08-13 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pro_category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='pro_gallery',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
